name: fall_detect
channels:
  - defaults
  - conda-forge
  - pypi
dependencies:
  - python=3.12.5
  - pip=25.0
  - setuptools=75.8.0
  - wheel=0.45.1
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - ipykernel
  - jupyter
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - ca-certificates
  - openssl
  - zlib
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - bleach
  - brotli-python
  - bzip2
  - cffi
  - charset-normalizer
  - colorama
  - comm
  - debugpy
  - decorator
  - defusedxml
  - executing
  - expat
  - h11
  - idna
  - jedi
  - jinja2
  - json5
  - jsonschema
  - jsonschema-specifications
  - jupyter-lsp
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab_pygments
  - jupyterlab_server
  - krb5
  - libffi
  - libpng
  - libpq
  - libsodium
  - lz4-c
  - markupsafe
  - matplotlib-inline
  - mistune
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - nest-asyncio
  - notebook
  - notebook-shim
  - openssl
  - overrides
  - packaging
  - pandoc
  - pandocfilters
  - parso
  - platformdirs
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pure_eval
  - pycparser
  - pygments
  - pyqt
  - pyqt6-sip
  - pysocks
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - pywin32
  - pywinpty
  - pyyaml
  - pyzmq
  - qtbase
  - qtconsole
  - qtdeclarative
  - qtpy
  - qtsvg
  - qttools
  - qtwebchannel
  - qtwebsockets
  - referencing
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - send2trash
  - sip
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - tinycss2
  - tk
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - vc
  - vs2015_runtime
  - wcwidth
  - webencodings
  - websocket-client
  - widgetsnbextension
  - win_inet_pton
  - winpty
  - xz
  - yaml
  - zeromq
  - zlib
  - zstd
  - pip:
      - absl-py==2.2.0
      - astunparse==1.6.3
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.13.1
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - httpx==0.27.0
      - huggingface-hub==0.29.3
      - jax==0.5.3
      - jaxlib==0.5.3
      - joblib==1.4.2
      - keras==3.9.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mediapipe==0.10.21
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cudnn-cu12==9.3.0.75
      - nvidia-pyindex==1.0.9
      - opencv-contrib-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.14.1
      - pandas==2.2.3
      - pillow==11.1.0
      - protobuf==4.25.6
      - pyparsing==3.2.3
      - pytz==2025.2
      - rarfile==4.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - sounddevice==0.5.1
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.50.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
